---
name: 'Custom CML-TPI'
description: 'Use a custom git/ref version of CML/TPI for hacky testing'
author: 'Daniel Barnes'

inputs:
  cml:
    descripton: 'git branch to use'
    required: false
    default: 'master'
  tpi:
    descripton: 'git branch to use'
    required: false
    default: 'master'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: iterative/terraform-provider-iterative
        ref: ${{ inputs.tpi }}
        path: terraform-provider-iterative
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'
    - name: Hack new tpi
      shell: bash
      run: |
        pushd terraform-provider-iterative
        make build
        make install
        popd
    - uses: actions/checkout@v3
      with:
        repository: iterative/cml
        ref: ${{ inputs.cml }}
        path: cml
    - name: Hack new cml
      shell: bash
      run: |
       pushd cml
       npm install
       sed -i "s/default: '>= 0.9.10'/default: ''/g" bin/cml/runner.js
       sed -i 's/source = "iterative\/iterative"/source = "github.com\/iterative\/iterative"/g' src/terraform.js
       sed -i 's/return template;/console.log(template);return template;/g' src/terraform.js
       npm install --global .
       popd
